"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url

# base directory of project
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment variable for security
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Load from environment variable - will be False in production
DEBUG = config('DEBUG', default=False, cast=bool)

# allowed hosts for the website
# In production, add your domain here
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# apps installed in this project
INSTALLED_APPS = [
    'django.contrib.admin',  # admin panel
    'django.contrib.auth',  # user authentication
    'django.contrib.contenttypes',  # content types framework
    'django.contrib.sessions',  # session framework
    'django.contrib.messages',  # messaging framework
    'django.contrib.staticfiles',  # static files management
    'tracker',  # my mood tracker app
]

# middleware for security and functionality
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# main url configuration file
ROOT_URLCONF = 'config.urls'

# template settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # directories for templates
        'APP_DIRS': True,  # look for templates in app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# wsgi application for deployment
WSGI_APPLICATION = 'config.wsgi.application'

# database configuration
# Uses DATABASE_URL in production (PostgreSQL), falls back to SQLite locally
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}

# password validation rules
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.'
             'UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.'
             'CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.'
             'NumericPasswordValidator'},
]


# language for the site
LANGUAGE_CODE = 'en-us'

# timezone
TIME_ZONE = 'UTC'

# enable internationalization
USE_I18N = True

# enable timezone support
USE_TZ = True


# CSRF trusted origins (for ngrok and external testing)
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=str)
if CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS.split(',') if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# redirect to home page after login
LOGIN_REDIRECT_URL = 'home'
# redirect to home page after logout
LOGOUT_REDIRECT_URL = 'home'
