# Generated by Django 6.0.1 on 2026-02-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("link", models.URLField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("adhd", "ADHD"),
                            ("depression", "Depression"),
                            ("anxiety", "Anxiety"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Resources",
                "ordering": ["category", "title"],
            },
        ),
    ]
