# Generated by Django 6.0.1 on 2026-02-08

from django.db import migrations


def add_adhd_resources(apps, schema_editor):
    Resource = apps.get_model("tracker", "Resource")
    resources = [
        {
            "title": "ADHD Ireland (NGO)",
            "description": "Irish charity providing education, advocacy, and support services for people with ADHD.",
            "link": "https://adhdireland.ie/",
            "category": "adhd",
        },
        {
            "title": "ADHD Europe (NGO)",
            "description": "European NGO network advancing ADHD awareness, policy, and community support.",
            "link": "https://www.adhdeurope.eu/",
            "category": "adhd",
        },
        {
            "title": "NHS: ADHD overview",
            "description": "Symptoms, how diagnosis is made, and treatment options for children and adults.",
            "link": "https://www.nhs.uk/conditions/attention-deficit-hyperactivity-disorder-adhd/",
            "category": "adhd",
        },
        {
            "title": "NICE Guideline NG87: ADHD",
            "description": "Evidence-based guidance covering assessment, diagnosis, medication, and therapy.",
            "link": "https://www.nice.org.uk/guidance/ng87",
            "category": "adhd",
        },
        {
            "title": "CDC: ADHD",
            "description": "Overview of ADHD, diagnostic considerations, and treatment pathways.",
            "link": "https://www.cdc.gov/ncbddd/adhd/",
            "category": "adhd",
        },
    ]

    for item in resources:
        Resource.objects.get_or_create(
            title=item["title"],
            defaults=item,
        )


def remove_adhd_resources(apps, schema_editor):
    Resource = apps.get_model("tracker", "Resource")
    titles = [
        "ADHD Ireland (NGO)",
        "ADHD Europe (NGO)",
        "NHS: ADHD overview",
        "NICE Guideline NG87: ADHD",
        "CDC: ADHD",
    ]
    Resource.objects.filter(title__in=titles, category="adhd").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_resource"),
    ]

    operations = [
        migrations.RunPython(add_adhd_resources, remove_adhd_resources),
    ]
