# Generated by Django 6.0.1 on 2026-02-08

from django.db import migrations


def add_more_resources(apps, schema_editor):
    Resource = apps.get_model("tracker", "Resource")
    resources = [
        {
            "title": "Aware (Ireland) - Depression Support",
            "description": "Irish charity supporting people affected by depression, bipolar disorder, and mood-related conditions.",
            "link": "https://aware.ie/",
            "category": "depression",
        },
        {
            "title": "Mental Health Ireland (NGO)",
            "description": "National Irish charity promoting mental health awareness, education, and community support.",
            "link": "https://www.mentalhealthireland.ie/",
            "category": "general",
        },
        {
            "title": "Anxiety Ireland (NGO)",
            "description": "Irish NGO providing support, education, and services for anxiety and related conditions.",
            "link": "https://www.anxietyireland.ie/",
            "category": "anxiety",
        },
        {
            "title": "Mental Health Europe (EU NGO)",
            "description": "European NGO network advocating for better mental health policy and community support.",
            "link": "https://www.mhe-sme.org/",
            "category": "general",
        },
        {
            "title": "NHS: Clinical depression",
            "description": "Overview of depression symptoms, diagnosis, and treatment pathways.",
            "link": "https://www.nhs.uk/mental-health/conditions/clinical-depression/overview/",
            "category": "depression",
        },
        {
            "title": "NHS: Generalised anxiety disorder",
            "description": "Symptoms, diagnosis, and treatment options for anxiety disorders.",
            "link": "https://www.nhs.uk/mental-health/conditions/generalised-anxiety-disorder/overview/",
            "category": "anxiety",
        },
        {
            "title": "WHO: Mental health",
            "description": "Global overview of mental health, care, and wellbeing resources.",
            "link": "https://www.who.int/health-topics/mental-health",
            "category": "general",
        },
        {
            "title": "WHO: Depression",
            "description": "Evidence-based overview of depression, impact, and treatment.",
            "link": "https://www.who.int/news-room/fact-sheets/detail/depression",
            "category": "depression",
        },
        {
            "title": "WHO: Anxiety disorders",
            "description": "Facts and guidance about anxiety disorders and care.",
            "link": "https://www.who.int/news-room/fact-sheets/detail/anxiety-disorders",
            "category": "anxiety",
        },
    ]

    for item in resources:
        Resource.objects.get_or_create(
            title=item["title"],
            defaults=item,
        )


def remove_more_resources(apps, schema_editor):
    Resource = apps.get_model("tracker", "Resource")
    titles = [
        "Aware (Ireland) - Depression Support",
        "Mental Health Ireland (NGO)",
        "Anxiety Ireland (NGO)",
        "Mental Health Europe (EU NGO)",
        "NHS: Clinical depression",
        "NHS: Generalised anxiety disorder",
        "WHO: Mental health",
        "WHO: Depression",
        "WHO: Anxiety disorders",
    ]
    Resource.objects.filter(title__in=titles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_add_adhd_resources"),
    ]

    operations = [
        migrations.RunPython(add_more_resources, remove_more_resources),
    ]
