# Generated by Django 6.0.1 on 2026-02-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_add_more_resources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="mood_score",
            field=models.IntegerField(
                choices=[
                    (0, "Very Low"),
                    (1, "Low"),
                    (2, "Below Average"),
                    (3, "Slightly Below Average"),
                    (4, "Average"),
                    (5, "Slightly Above Average"),
                    (6, "Good"),
                    (7, "Very Good"),
                    (8, "Great"),
                    (9, "Excellent"),
                    (10, "Outstanding"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="notes",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
